version: "3.9"

services:
  backend:
    build: ./backend
    container_name: oci-terraform-backend
    ports:
      - "8000:8000"
    volumes:
      - terraform_workspace:/app/terraform_workspace
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    security_opt:
      - seccomp:unconfined
      - label:disable

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://134.185.162.105:8000
    container_name: oci-terraform-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - label:disable

volumes:
  terraform_workspace:
